# Generated by Django 3.2.14 on 2022-08-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220824_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_id',
            new_name='stripe_pid',
        ),
    ]
