# Generated by Django 3.2.14 on 2022-08-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_title', models.CharField(max_length=254)),
                ('tour_distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tour_description', models.TextField()),
                ('tour_time_length', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tour_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tour_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.guide')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.level')),
            ],
        ),
    ]
