# Generated by Django 3.2.14 on 2022-08-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_distance',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_speed',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_time_length',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
