# Generated by Django 3.2.14 on 2022-08-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220810_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
