# Generated by Django 3.2.14 on 2022-08-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220817_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
