# Generated by Django 3.2.14 on 2022-08-17 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_guide_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='experience',
        ),
    ]
