# Generated by Django 3.2.14 on 2022-08-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_guide_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
