# Generated by Django 3.2.14 on 2022-08-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_guide_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='certificates',
            field=models.CharField(default='description', max_length=254),
        ),
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='nationality',
            field=models.CharField(default='description', max_length=254),
        ),
    ]
