# Generated by Django 3.2.14 on 2022-08-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220817_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tour_quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
