# Generated by Django 3.2.14 on 2022-08-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_tour_tour_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='tour_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
