# Generated by Django 3.2.14 on 2022-08-19 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_tour_tour_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='tour_quantity',
        ),
    ]
